import { NextApiResponse } from 'next'
//import { getTemplate } from 'data/figma'
import { defaults } from 'static/invoice'
import { defaultTemplates } from 'static/defaultTemplates'

export default async (req, res: NextApiResponse) => {
  const templateID = req.query.template || defaults.template
  //const template = await getTemplate(templateID)
  const existingTempalte = defaultTemplates.map(({ template }) => template).includes(templateID)
  if (existingTempalte) res.setHeader('Cache-Control', 's-maxage=60, stale-while-revalidate')
  res.json(template)
}

const template = {
  document: {
    id: '0:0',
    name: 'Document',
    type: 'DOCUMENT',
    children: [
      {
        id: '0:1',
        name: 'Page 1',
        type: 'CANVAS',
        children: [
          {
            id: '1:2',
            name: 'Frame 1',
            type: 'FRAME',
            blendMode: 'PASS_THROUGH',
            children: [
              {
                id: '1:6',
                name: 'Frame 1',
                type: 'FRAME',
                blendMode: 'PASS_THROUGH',
                children: [
                  {
                    id: '1:7',
                    name: 'Something here',
                    type: 'TEXT',
                    blendMode: 'PASS_THROUGH',
                    absoluteBoundingBox: {
                      x: 20,
                      y: 120.5,
                      width: 561,
                      height: 16,
                    },
                    constraints: {
                      vertical: 'TOP',
                      horizontal: 'LEFT',
                    },
                    layoutAlign: 'STRETCH',
                    layoutGrow: 0,
                    fills: [
                      {
                        blendMode: 'NORMAL',
                        type: 'SOLID',
                        color: {
                          r: 0,
                          g: 0,
                          b: 0,
                          a: 1,
                        },
                      },
                    ],
                    strokes: [],
                    strokeWeight: 1,
                    strokeAlign: 'OUTSIDE',
                    effects: [],
                    characters: 'Something here',
                    style: {
                      fontFamily: 'Arial',
                      fontPostScriptName: 'ArialMT',
                      fontWeight: 400,
                      textAutoResize: 'HEIGHT',
                      fontSize: 14,
                      textAlignHorizontal: 'CENTER',
                      textAlignVertical: 'TOP',
                      letterSpacing: 0,
                      lineHeightPx: 16.40625,
                      lineHeightPercent: 100,
                      lineHeightUnit: 'INTRINSIC_%',
                    },
                    characterStyleOverrides: [],
                    styleOverrideTable: {},
                  },
                  {
                    id: '1:3',
                    name: 'Hello world!',
                    type: 'TEXT',
                    blendMode: 'PASS_THROUGH',
                    absoluteBoundingBox: {
                      x: 20,
                      y: 136.5,
                      width: 561,
                      height: 55,
                    },
                    constraints: {
                      vertical: 'CENTER',
                      horizontal: 'CENTER',
                    },
                    layoutAlign: 'STRETCH',
                    layoutGrow: 0,
                    fills: [
                      {
                        blendMode: 'NORMAL',
                        type: 'SOLID',
                        color: {
                          r: 0,
                          g: 0,
                          b: 0,
                          a: 1,
                        },
                      },
                    ],
                    strokes: [],
                    strokeWeight: 4,
                    strokeAlign: 'OUTSIDE',
                    effects: [],
                    characters: 'Hello world!',
                    style: {
                      fontFamily: 'Arial',
                      fontPostScriptName: 'ArialMT',
                      fontWeight: 400,
                      textAutoResize: 'HEIGHT',
                      fontSize: 48,
                      textAlignHorizontal: 'CENTER',
                      textAlignVertical: 'TOP',
                      letterSpacing: 0,
                      lineHeightPx: 56.25,
                      lineHeightPercent: 100,
                      lineHeightUnit: 'INTRINSIC_%',
                    },
                    characterStyleOverrides: [],
                    styleOverrideTable: {},
                  },
                ],
                absoluteBoundingBox: {
                  x: 20,
                  y: 46,
                  width: 561,
                  height: 220,
                },
                constraints: {
                  vertical: 'TOP',
                  horizontal: 'LEFT',
                },
                clipsContent: false,
                background: [],
                fills: [],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: 'INSIDE',
                backgroundColor: {
                  r: 0,
                  g: 0,
                  b: 0,
                  a: 0,
                },
                layoutGrids: [],
                layoutMode: 'VERTICAL',
                counterAxisSizingMode: 'FIXED',
                primaryAxisSizingMode: 'FIXED',
                counterAxisAlignItems: 'CENTER',
                primaryAxisAlignItems: 'CENTER',
                effects: [],
              },
              {
                id: '3:1',
                name: 'Hi.',
                type: 'TEXT',
                blendMode: 'PASS_THROUGH',
                absoluteBoundingBox: {
                  x: 546,
                  y: 19.5,
                  width: 35,
                  height: 32,
                },
                constraints: {
                  vertical: 'CENTER',
                  horizontal: 'CENTER',
                },
                fills: [
                  {
                    blendMode: 'NORMAL',
                    type: 'SOLID',
                    color: {
                      r: 0,
                      g: 0,
                      b: 0,
                      a: 1,
                    },
                  },
                ],
                strokes: [],
                strokeWeight: 4,
                strokeAlign: 'OUTSIDE',
                effects: [],
                characters: 'Hi.',
                style: {
                  fontFamily: 'Arial',
                  fontPostScriptName: 'ArialMT',
                  fontWeight: 400,
                  textAutoResize: 'WIDTH_AND_HEIGHT',
                  fontSize: 28,
                  textAlignHorizontal: 'RIGHT',
                  textAlignVertical: 'TOP',
                  letterSpacing: 0,
                  lineHeightPx: 32.8125,
                  lineHeightPercent: 100,
                  lineHeightUnit: 'INTRINSIC_%',
                },
                characterStyleOverrides: [],
                styleOverrideTable: {},
              },
              {
                id: '3:2',
                name: 'Hello',
                type: 'TEXT',
                blendMode: 'PASS_THROUGH',
                absoluteBoundingBox: {
                  x: 20,
                  y: 265.5,
                  width: 64,
                  height: 32,
                },
                constraints: {
                  vertical: 'CENTER',
                  horizontal: 'CENTER',
                },
                fills: [
                  {
                    blendMode: 'NORMAL',
                    type: 'SOLID',
                    color: {
                      r: 0,
                      g: 0,
                      b: 0,
                      a: 1,
                    },
                  },
                ],
                strokes: [],
                strokeWeight: 4,
                strokeAlign: 'OUTSIDE',
                effects: [],
                characters: 'Hello',
                style: {
                  fontFamily: 'Arial',
                  fontPostScriptName: 'ArialMT',
                  fontWeight: 400,
                  textAutoResize: 'WIDTH_AND_HEIGHT',
                  fontSize: 28,
                  textAlignHorizontal: 'LEFT',
                  textAlignVertical: 'TOP',
                  letterSpacing: 0,
                  lineHeightPx: 32.8125,
                  lineHeightPercent: 100,
                  lineHeightUnit: 'INTRINSIC_%',
                },
                characterStyleOverrides: [],
                styleOverrideTable: {},
              },
            ],
            absoluteBoundingBox: {
              x: 0,
              y: 2.842170943040401e-14,
              width: 600,
              height: 315,
            },
            constraints: {
              vertical: 'TOP',
              horizontal: 'LEFT',
            },
            clipsContent: true,
            background: [
              {
                blendMode: 'NORMAL',
                type: 'SOLID',
                color: {
                  r: 0.9749711155891418,
                  g: 0.9387104511260986,
                  b: 0.8454688787460327,
                  a: 1,
                },
              },
            ],
            fills: [
              {
                blendMode: 'NORMAL',
                type: 'SOLID',
                color: {
                  r: 0.9749711155891418,
                  g: 0.9387104511260986,
                  b: 0.8454688787460327,
                  a: 1,
                },
              },
            ],
            strokes: [],
            strokeWeight: 1,
            strokeAlign: 'INSIDE',
            backgroundColor: {
              r: 0.9749711155891418,
              g: 0.9387104511260986,
              b: 0.8454688787460327,
              a: 1,
            },
            layoutGrids: [],
            effects: [],
          },
          {
            id: '12:1',
            name: 'Frame 2',
            type: 'FRAME',
            blendMode: 'PASS_THROUGH',
            children: [
              {
                id: '12:19',
                name: 'Logo',
                type: 'BOOLEAN_OPERATION',
                blendMode: 'PASS_THROUGH',
                booleanOperation: 'UNION',
                children: [
                  {
                    id: '12:8',
                    name: 'Vector',
                    type: 'VECTOR',
                    blendMode: 'PASS_THROUGH',
                    absoluteBoundingBox: {
                      x: 31.6234130859375,
                      y: 376,
                      width: 17.430402755737305,
                      height: 23.967063903808594,
                    },
                    constraints: {
                      vertical: 'SCALE',
                      horizontal: 'SCALE',
                    },
                    fills: [
                      {
                        blendMode: 'NORMAL',
                        type: 'SOLID',
                        color: {
                          r: 1,
                          g: 1,
                          b: 1,
                          a: 1,
                        },
                      },
                    ],
                    strokes: [],
                    strokeWeight: 1,
                    strokeAlign: 'INSIDE',
                    effects: [],
                  },
                  {
                    id: '12:18',
                    name: 'dashbird',
                    type: 'VECTOR',
                    blendMode: 'PASS_THROUGH',
                    absoluteBoundingBox: {
                      x: 57.498046875,
                      y: 381.5709228515625,
                      width: 67.60687255859375,
                      height: 12.6171875,
                    },
                    constraints: {
                      vertical: 'SCALE',
                      horizontal: 'SCALE',
                    },
                    fills: [
                      {
                        blendMode: 'NORMAL',
                        type: 'SOLID',
                        color: {
                          r: 1,
                          g: 1,
                          b: 1,
                          a: 1,
                        },
                      },
                    ],
                    strokes: [],
                    strokeWeight: 1,
                    strokeAlign: 'OUTSIDE',
                    effects: [],
                  },
                ],
                absoluteBoundingBox: {
                  x: 31.6234130859375,
                  y: 376,
                  width: 93.48150634765625,
                  height: 23.967063903808594,
                },
                constraints: {
                  vertical: 'TOP',
                  horizontal: 'LEFT',
                },
                fills: [
                  {
                    blendMode: 'NORMAL',
                    type: 'SOLID',
                    color: {
                      r: 1,
                      g: 1,
                      b: 1,
                      a: 1,
                    },
                  },
                ],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: 'OUTSIDE',
                effects: [],
              },
              {
                id: '13:2',
                name: 'group',
                type: 'FRAME',
                blendMode: 'PASS_THROUGH',
                children: [
                  {
                    id: '12:11',
                    name: 'Debugging with dashbird',
                    type: 'TEXT',
                    blendMode: 'PASS_THROUGH',
                    absoluteBoundingBox: {
                      x: 29.6234130859375,
                      y: 496.502685546875,
                      width: 298.2283630371094,
                      height: 16,
                    },
                    constraints: {
                      vertical: 'SCALE',
                      horizontal: 'CENTER',
                    },
                    layoutAlign: 'STRETCH',
                    layoutGrow: 0,
                    fills: [
                      {
                        blendMode: 'NORMAL',
                        type: 'SOLID',
                        color: {
                          r: 1,
                          g: 1,
                          b: 1,
                          a: 1,
                        },
                      },
                    ],
                    strokes: [],
                    strokeWeight: 1,
                    strokeAlign: 'OUTSIDE',
                    effects: [],
                    characters: 'Debugging with dashbird',
                    style: {
                      fontFamily: 'Kumbh Sans',
                      fontPostScriptName: 'KumbhSans-Regular',
                      fontWeight: 400,
                      textAutoResize: 'HEIGHT',
                      fontSize: 16,
                      textAlignHorizontal: 'LEFT',
                      textAlignVertical: 'TOP',
                      letterSpacing: -0.16,
                      lineHeightPx: 18.75,
                      lineHeightPercent: 100,
                      lineHeightUnit: 'INTRINSIC_%',
                    },
                    characterStyleOverrides: [],
                    styleOverrideTable: {},
                  },
                  {
                    id: '12:14',
                    name: 'title',
                    type: 'TEXT',
                    blendMode: 'PASS_THROUGH',
                    absoluteBoundingBox: {
                      x: 29.6234130859375,
                      y: 526.502685546875,
                      width: 298.2283630371094,
                      height: 99,
                    },
                    constraints: {
                      vertical: 'CENTER',
                      horizontal: 'CENTER',
                    },
                    layoutAlign: 'STRETCH',
                    layoutGrow: 0,
                    fills: [
                      {
                        blendMode: 'NORMAL',
                        type: 'SOLID',
                        color: {
                          r: 1,
                          g: 1,
                          b: 1,
                          a: 1,
                        },
                      },
                    ],
                    strokes: [],
                    strokeWeight: 1.6573697328567505,
                    strokeAlign: 'OUTSIDE',
                    effects: [],
                    characters: 'Resolving All API Gateway Request errors',
                    style: {
                      fontFamily: 'Kumbh Sans',
                      fontPostScriptName: 'KumbhSans-Bold',
                      fontWeight: 700,
                      textAutoResize: 'HEIGHT',
                      fontSize: 33.147396087646484,
                      textAlignHorizontal: 'LEFT',
                      textAlignVertical: 'TOP',
                      letterSpacing: -0.33147396087646486,
                      lineHeightPx: 38.8446044921875,
                      lineHeightPercent: 100,
                      lineHeightUnit: 'INTRINSIC_%',
                    },
                    characterStyleOverrides: [],
                    styleOverrideTable: {},
                  },
                ],
                absoluteBoundingBox: {
                  x: 29.6234130859375,
                  y: 496.502685546875,
                  width: 298.2283630371094,
                  height: 129,
                },
                constraints: {
                  vertical: 'BOTTOM',
                  horizontal: 'LEFT',
                },
                clipsContent: false,
                background: [],
                fills: [],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: 'INSIDE',
                backgroundColor: {
                  r: 0,
                  g: 0,
                  b: 0,
                  a: 0,
                },
                layoutGrids: [],
                layoutMode: 'VERTICAL',
                counterAxisSizingMode: 'FIXED',
                itemSpacing: 14,
                effects: [],
              },
              {
                id: '12:17',
                name: 'image 2',
                type: 'RECTANGLE',
                blendMode: 'PASS_THROUGH',
                absoluteBoundingBox: {
                  x: 327.851806640625,
                  y: 381.64910888671875,
                  width: 541.4657592773438,
                  height: 328.8174133300781,
                },
                preserveRatio: true,
                constraints: {
                  vertical: 'TOP',
                  horizontal: 'LEFT',
                },
                fills: [
                  {
                    blendMode: 'NORMAL',
                    type: 'IMAGE',
                    scaleMode: 'FILL',
                    imageRef: '259a52c097d80ba83da6e192f6f0ce371c14d43e',
                  },
                ],
                strokes: [],
                strokeWeight: 1,
                strokeAlign: 'INSIDE',
                effects: [],
              },
            ],
            absoluteBoundingBox: {
              x: 0,
              y: 346,
              width: 600,
              height: 315,
            },
            constraints: {
              vertical: 'TOP',
              horizontal: 'LEFT',
            },
            clipsContent: true,
            background: [
              {
                blendMode: 'NORMAL',
                type: 'GRADIENT_LINEAR',
                gradientHandlePositions: [
                  {
                    x: 0.6469483819298794,
                    y: 1.0000000193323415,
                  },
                  {
                    x: -5.551115123125783e-17,
                    y: -4.440892098500626e-16,
                  },
                  {
                    x: 1.146948279009418,
                    y: -0.17360250680241984,
                  },
                ],
                gradientStops: [
                  {
                    color: {
                      r: 0,
                      g: 0,
                      b: 0,
                      a: 1,
                    },
                    position: 0,
                  },
                  {
                    color: {
                      r: 0.24664363265037537,
                      g: 0,
                      b: 0.30830445885658264,
                      a: 1,
                    },
                    position: 1,
                  },
                ],
              },
            ],
            fills: [
              {
                blendMode: 'NORMAL',
                type: 'GRADIENT_LINEAR',
                gradientHandlePositions: [
                  {
                    x: 0.6469483819298794,
                    y: 1.0000000193323415,
                  },
                  {
                    x: -5.551115123125783e-17,
                    y: -4.440892098500626e-16,
                  },
                  {
                    x: 1.146948279009418,
                    y: -0.17360250680241984,
                  },
                ],
                gradientStops: [
                  {
                    color: {
                      r: 0,
                      g: 0,
                      b: 0,
                      a: 1,
                    },
                    position: 0,
                  },
                  {
                    color: {
                      r: 0.24664363265037537,
                      g: 0,
                      b: 0.30830445885658264,
                      a: 1,
                    },
                    position: 1,
                  },
                ],
              },
            ],
            strokes: [],
            strokeWeight: 1,
            strokeAlign: 'INSIDE',
            backgroundColor: {
              r: 0,
              g: 0,
              b: 0,
              a: 0,
            },
            layoutGrids: [],
            exportSettings: [
              {
                suffix: '',
                format: 'PNG',
                constraint: {
                  type: 'SCALE',
                  value: 2,
                },
              },
            ],
            effects: [],
          },
          {
            id: '13:9',
            name: '315-',
            type: 'TEXT',
            blendMode: 'PASS_THROUGH',
            absoluteBoundingBox: {
              x: -295,
              y: 415,
              width: 72,
              height: 33,
            },
            constraints: {
              vertical: 'TOP',
              horizontal: 'LEFT',
            },
            fills: [
              {
                blendMode: 'NORMAL',
                type: 'SOLID',
                color: {
                  r: 0,
                  g: 0,
                  b: 0,
                  a: 1,
                },
              },
            ],
            strokes: [],
            strokeWeight: 1,
            strokeAlign: 'OUTSIDE',
            effects: [],
            characters: '315-',
            style: {
              fontFamily: 'Kumbh Sans',
              fontPostScriptName: 'KumbhSans-Bold',
              fontWeight: 700,
              textAutoResize: 'WIDTH_AND_HEIGHT',
              fontSize: 33.147396087646484,
              textAlignHorizontal: 'LEFT',
              textAlignVertical: 'TOP',
              letterSpacing: -0.33147396087646486,
              lineHeightPx: 38.8446044921875,
              lineHeightPercent: 100,
              lineHeightUnit: 'INTRINSIC_%',
            },
            characterStyleOverrides: [],
            styleOverrideTable: {},
          },
        ],
        backgroundColor: {
          r: 0.8980392217636108,
          g: 0.8980392217636108,
          b: 0.8980392217636108,
          a: 1,
        },
        prototypeStartNodeID: null,
        prototypeDevice: {
          type: 'NONE',
          rotation: 'NONE',
        },
      },
    ],
  },
  components: {},
  schemaVersion: 0,
  styles: {},
  name: 'Amorphic render test',
  lastModified: '2021-06-20T14:19:32Z',
  thumbnailUrl:
    'https://s3-alpha-sig.figma.com/thumbnails/21a32016-dc99-4d03-8763-5f27d1c8c4d6?Expires=1624838400&Signature=PDFOiRqYtLcHMhy3GpenkxcPe46yOa2NpynwkHhMygnmDEclzK-FYunIthS5hQ8DCHJEj-ts6Ko2p4rxgE-xlfDz6IGyULvHoKK1AvCJd3rSWFVOcjaSM9HsbGfPbuUc1~1tzFFkHctHbg1TlQgS7BnfdYBLNfwO1gGveIoEQ6bnNsz2D3EwF6Yycared9ayP6ixwfViGzvFwzqk0uMeyJsaX-qEf0VOyTx-NPn7JCDabUKacuYeHfcSN-jfhgRV9NOjIFHW0~OtNSZTWODoTQQIMTDotc6iooBto~Nxt-Ie6Cmn7e81NekQeoh5fyW7rz9GYEzzLxAQGMHyUeIBSQ__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA',
  version: '927209336',
  role: 'owner',
}
