export const template = {
  id: '0:2',
  name: 'page',
  type: 'FRAME',
  blendMode: 'PASS_THROUGH',
  children: [
    {
      id: '1:161',
      name: 'Footer',
      type: 'GROUP',
      blendMode: 'PASS_THROUGH',
      children: [
        {
          id: '0:6',
          name: 'invoicenr-and-bankcode',
          type: 'TEXT',
          blendMode: 'NORMAL',
          opacity: 0.5,
          absoluteBoundingBox: {
            x: 413,
            y: 754,
            width: 122,
            height: 45,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          fills: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
            },
          ],
          strokes: [],
          strokeWeight: 0,
          strokeAlign: 'CENTER',
          exportSettings: [],
          effects: [],
          characters: 'Arve nr: 2019052201\nLHV: EE907700771001360230\n',
          style: {
            fontFamily: 'Wigrum',
            fontPostScriptName: 'Wigrum-Regular',
            fontWeight: 400,
            textAutoResize: 'WIDTH_AND_HEIGHT',
            fontSize: 9,
            textAlignHorizontal: 'RIGHT',
            textAlignVertical: 'TOP',
            letterSpacing: 0,
            lineHeightPx: 15,
            lineHeightPercent: 142.22222900390625,
            lineHeightPercentFontSize: 166.6666717529297,
            lineHeightUnit: 'PIXELS',
          },
          characterStyleOverrides: [],
          styleOverrideTable: {},
        },
        {
          id: '0:7',
          name: 'phone',
          type: 'TEXT',
          blendMode: 'NORMAL',
          opacity: 0.5,
          absoluteBoundingBox: {
            x: 308,
            y: 754,
            width: 67,
            height: 15,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          fills: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
            },
          ],
          strokes: [],
          strokeWeight: 0,
          strokeAlign: 'CENTER',
          exportSettings: [],
          effects: [],
          characters: '+372 590 13 105',
          style: {
            fontFamily: 'Wigrum',
            fontPostScriptName: 'Wigrum-Regular',
            fontWeight: 400,
            textAutoResize: 'WIDTH_AND_HEIGHT',
            fontSize: 9,
            textAlignHorizontal: 'LEFT',
            textAlignVertical: 'TOP',
            letterSpacing: 0,
            lineHeightPx: 15,
            lineHeightPercent: 142.22222900390625,
            lineHeightPercentFontSize: 166.6666717529297,
            lineHeightUnit: 'PIXELS',
          },
          characterStyleOverrides: [],
          styleOverrideTable: {},
        },
        {
          id: '0:5',
          name: 'website-and-email',
          type: 'TEXT',
          blendMode: 'NORMAL',
          opacity: 0.5,
          absoluteBoundingBox: {
            x: 169,
            y: 754,
            width: 105,
            height: 30,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          fills: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
            },
          ],
          strokes: [],
          strokeWeight: 0,
          strokeAlign: 'CENTER',
          exportSettings: [],
          effects: [],
          characters: 'mikkmartin.co\nmikk.martin@gmail.com',
          style: {
            fontFamily: 'Wigrum',
            fontPostScriptName: 'Wigrum-Regular',
            fontWeight: 400,
            textAutoResize: 'WIDTH_AND_HEIGHT',
            fontSize: 9,
            textAlignHorizontal: 'LEFT',
            textAlignVertical: 'TOP',
            letterSpacing: 0,
            lineHeightPx: 15,
            lineHeightPercent: 142.22222900390625,
            lineHeightPercentFontSize: 166.6666717529297,
            lineHeightUnit: 'PIXELS',
          },
          characterStyleOverrides: [],
          styleOverrideTable: {},
        },
        {
          id: '0:4',
          name: 'firm-name-and-registrationnr',
          type: 'TEXT',
          blendMode: 'NORMAL',
          opacity: 0.5,
          absoluteBoundingBox: {
            x: 56,
            y: 754,
            width: 73,
            height: 30,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          fills: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
            },
          ],
          strokes: [],
          strokeWeight: 0,
          strokeAlign: 'CENTER',
          exportSettings: [],
          effects: [],
          characters: 'OÜ Mikk Martin\nReg.nr: 12702285',
          style: {
            fontFamily: 'Wigrum',
            fontPostScriptName: 'Wigrum-Regular',
            fontWeight: 400,
            textAutoResize: 'WIDTH_AND_HEIGHT',
            fontSize: 9,
            textAlignHorizontal: 'LEFT',
            textAlignVertical: 'TOP',
            letterSpacing: 0,
            lineHeightPx: 15,
            lineHeightPercent: 142.22222900390625,
            lineHeightPercentFontSize: 166.6666717529297,
            lineHeightUnit: 'PIXELS',
          },
          characterStyleOverrides: [],
          styleOverrideTable: {},
        },
      ],
      absoluteBoundingBox: {
        x: 56,
        y: 754,
        width: 479,
        height: 45,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      clipsContent: false,
      background: [],
      fills: [],
      strokes: [],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      backgroundColor: {
        r: 0,
        g: 0,
        b: 0,
        a: 0,
      },
      effects: [],
    },
    {
      id: '1:56',
      name: 'Body Content',
      type: 'FRAME',
      blendMode: 'PASS_THROUGH',
      children: [
        {
          id: '1:44',
          name: 'sybol-list-item',
          type: 'INSTANCE',
          blendMode: 'PASS_THROUGH',
          children: [
            {
              id: 'I1:44;0:10',
              name: 'Total',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 513,
                y: 310,
                width: 27,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '150€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:44;0:13',
              name: 'Quantity',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 441,
                y: 310,
                width: 7,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '1',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:44;0:11',
              name: 'Price',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 333,
                y: 310,
                width: 27,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '150€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:44;0:14',
              name: 'Description',
              type: 'TEXT',
              blendMode: 'NORMAL',
              opacity: 0.5018656849861145,
              absoluteBoundingBox: {
                x: 56,
                y: 326,
                width: 258,
                height: 11,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: 'Kaks vooru loovsuunitluse paika panemist',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Light',
                fontWeight: 300,
                textAutoResize: 'HEIGHT',
                fontSize: 11,
                textAlignHorizontal: 'LEFT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 12.890625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:44;0:12',
              name: 'Title',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 56,
                y: 310,
                width: 95,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: 'Esteetika kollaaž',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'LEFT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
          ],
          absoluteBoundingBox: {
            x: 56,
            y: 310,
            width: 484,
            height: 27,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          layoutAlign: 'CENTER',
          clipsContent: false,
          background: [],
          fills: [],
          strokes: [],
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          backgroundColor: {
            r: 0,
            g: 0,
            b: 0,
            a: 0,
          },
          effects: [],
          componentId: '1:37',
        },
        {
          id: '1:57',
          name: 'Group 2',
          type: 'INSTANCE',
          blendMode: 'PASS_THROUGH',
          children: [
            {
              id: 'I1:57;0:10',
              name: 'Total',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 513,
                y: 357,
                width: 27,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '750€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:57;0:13',
              name: 'Quantity',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 441,
                y: 357,
                width: 7,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '1',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:57;0:11',
              name: 'Price',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 333,
                y: 357,
                width: 27,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '750€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:57;0:14',
              name: 'Description',
              type: 'TEXT',
              blendMode: 'NORMAL',
              opacity: 0.5018656849861145,
              absoluteBoundingBox: {
                x: 56,
                y: 373,
                width: 258,
                height: 11,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: 'Visuaalse keele välja töötamine',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Light',
                fontWeight: 300,
                textAutoResize: 'HEIGHT',
                fontSize: 11,
                textAlignHorizontal: 'LEFT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 12.890625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:57;0:12',
              name: 'Title',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 56,
                y: 357,
                width: 181,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: 'Visuaalse keele välja töötamine',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'LEFT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
          ],
          absoluteBoundingBox: {
            x: 56,
            y: 357,
            width: 484,
            height: 27,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          layoutAlign: 'CENTER',
          clipsContent: false,
          background: [],
          fills: [],
          strokes: [],
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          backgroundColor: {
            r: 0,
            g: 0,
            b: 0,
            a: 0,
          },
          effects: [],
          componentId: '1:37',
        },
        {
          id: '1:65',
          name: 'Group 3',
          type: 'INSTANCE',
          blendMode: 'PASS_THROUGH',
          children: [
            {
              id: 'I1:65;0:10',
              name: 'Total',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 503,
                y: 404,
                width: 37,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '1 500€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:65;0:13',
              name: 'Quantity',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 441,
                y: 404,
                width: 7,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '1',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:65;0:11',
              name: 'Price',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 323,
                y: 404,
                width: 37,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '1 500€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:65;0:14',
              name: 'Description',
              type: 'TEXT',
              blendMode: 'NORMAL',
              opacity: 0.5018656849861145,
              absoluteBoundingBox: {
                x: 56,
                y: 420,
                width: 258,
                height: 11,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: 'Disain kogu veebile',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Light',
                fontWeight: 300,
                textAutoResize: 'HEIGHT',
                fontSize: 11,
                textAlignHorizontal: 'LEFT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 12.890625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:65;0:12',
              name: 'Title',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 56,
                y: 404,
                width: 111,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: 'Disain kogu veebile',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'LEFT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
          ],
          absoluteBoundingBox: {
            x: 56,
            y: 404,
            width: 484,
            height: 27,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          layoutAlign: 'CENTER',
          clipsContent: false,
          background: [],
          fills: [],
          strokes: [],
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          backgroundColor: {
            r: 0,
            g: 0,
            b: 0,
            a: 0,
          },
          effects: [],
          componentId: '1:37',
        },
        {
          id: '1:71',
          name: 'Group 4',
          type: 'INSTANCE',
          blendMode: 'PASS_THROUGH',
          children: [
            {
              id: 'I1:71;0:10',
              name: 'Total',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 503,
                y: 451,
                width: 37,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '1 200€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:71;0:13',
              name: 'Quantity',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 441,
                y: 451,
                width: 7,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '1',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:71;0:11',
              name: 'Price',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 323,
                y: 451,
                width: 37,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: '1 200€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:71;0:14',
              name: 'Description',
              type: 'TEXT',
              blendMode: 'NORMAL',
              opacity: 0.5018656849861145,
              absoluteBoundingBox: {
                x: 56,
                y: 467,
                width: 258,
                height: 11,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: 'Täis implementatisoon uuele disainile',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Light',
                fontWeight: 300,
                textAutoResize: 'HEIGHT',
                fontSize: 11,
                textAlignHorizontal: 'LEFT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 12.890625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: 'I1:71;0:12',
              name: 'Title',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 56,
                y: 451,
                width: 139,
                height: 12,
              },
              constraints: {
                vertical: 'SCALE',
                horizontal: 'SCALE',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              effects: [],
              characters: 'Veebi implementatsioon',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'LEFT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 14.0625,
                lineHeightPercent: 100,
                lineHeightUnit: 'INTRINSIC_%',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
          ],
          absoluteBoundingBox: {
            x: 56,
            y: 451,
            width: 484,
            height: 27,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          layoutAlign: 'CENTER',
          clipsContent: false,
          background: [],
          fills: [],
          strokes: [],
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          backgroundColor: {
            r: 0,
            g: 0,
            b: 0,
            a: 0,
          },
          effects: [],
          componentId: '1:37',
        },
        {
          id: '1:78',
          name: 'Body-summary-conteinr',
          type: 'GROUP',
          blendMode: 'PASS_THROUGH',
          children: [
            {
              id: '1:82',
              name: 'to-pay-value',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 478,
                y: 564,
                width: 62,
                height: 25,
              },
              constraints: {
                vertical: 'TOP',
                horizontal: 'LEFT',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              exportSettings: [],
              effects: [],
              characters: '1 800.00€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Medium',
                fontWeight: 500,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 1,
                lineHeightPx: 25,
                lineHeightPercent: 177.7777862548828,
                lineHeightPercentFontSize: 208.3333282470703,
                lineHeightUnit: 'PIXELS',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: '1:79',
              name: 'to-pay-description',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 259,
                y: 564,
                width: 186,
                height: 25,
              },
              constraints: {
                vertical: 'TOP',
                horizontal: 'LEFT',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              exportSettings: [],
              effects: [],
              characters: 'Maksmisele kuuluv summa (EUR)',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 25,
                lineHeightPercent: 177.7777862548828,
                lineHeightPercentFontSize: 208.3333282470703,
                lineHeightUnit: 'PIXELS',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: '1:81',
              name: 'subtotals-values',
              type: 'TEXT',
              blendMode: 'PASS_THROUGH',
              absoluteBoundingBox: {
                x: 498,
                y: 498,
                width: 42,
                height: 45,
              },
              constraints: {
                vertical: 'TOP',
                horizontal: 'LEFT',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              exportSettings: [],
              effects: [],
              characters: '3 600€\n1 800€\n0€',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 1,
                lineHeightPx: 15,
                lineHeightPercent: 106.66667175292969,
                lineHeightPercentFontSize: 125,
                lineHeightUnit: 'PIXELS',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
            {
              id: '1:80',
              name: 'subtotals-descriptions',
              type: 'TEXT',
              blendMode: 'NORMAL',
              opacity: 0.5,
              absoluteBoundingBox: {
                x: 276,
                y: 498,
                width: 172,
                height: 60,
              },
              constraints: {
                vertical: 'TOP',
                horizontal: 'LEFT',
              },
              fills: [
                {
                  blendMode: 'NORMAL',
                  type: 'SOLID',
                  color: {
                    r: 0,
                    g: 0,
                    b: 0,
                    a: 1,
                  },
                },
              ],
              strokes: [],
              strokeWeight: 0,
              strokeAlign: 'CENTER',
              exportSettings: [],
              effects: [],
              characters: 'Kokku\nEelnevalt makstud\nKäibemaks (kohustus puudub)\n',
              style: {
                fontFamily: 'Wigrum',
                fontPostScriptName: 'Wigrum-Regular',
                fontWeight: 400,
                textAutoResize: 'WIDTH_AND_HEIGHT',
                fontSize: 12,
                textAlignHorizontal: 'RIGHT',
                textAlignVertical: 'TOP',
                letterSpacing: 0,
                lineHeightPx: 15,
                lineHeightPercent: 106.66667175292969,
                lineHeightPercentFontSize: 125,
                lineHeightUnit: 'PIXELS',
              },
              characterStyleOverrides: [],
              styleOverrideTable: {},
            },
          ],
          absoluteBoundingBox: {
            x: 259,
            y: 498,
            width: 281,
            height: 91,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          layoutAlign: 'MAX',
          clipsContent: false,
          background: [],
          fills: [],
          strokes: [],
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          backgroundColor: {
            r: 0,
            g: 0,
            b: 0,
            a: 0,
          },
          effects: [],
        },
      ],
      absoluteBoundingBox: {
        x: 56,
        y: 310,
        width: 484,
        height: 279,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'RIGHT',
      },
      clipsContent: true,
      background: [],
      fills: [],
      strokes: [],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      backgroundColor: {
        r: 0,
        g: 0,
        b: 0,
        a: 0,
      },
      layoutGrids: [],
      layoutMode: 'VERTICAL',
      itemSpacing: 20,
      effects: [],
    },
    {
      id: '0:24',
      name: 'label-summary',
      type: 'TEXT',
      blendMode: 'NORMAL',
      opacity: 0.5,
      absoluteBoundingBox: {
        x: 502,
        y: 275,
        width: 38,
        height: 9,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'SUMMA',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Medium',
        fontWeight: 500,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 9,
        textAlignHorizontal: 'RIGHT',
        textAlignVertical: 'TOP',
        letterSpacing: 1,
        lineHeightPx: 10.546875,
        lineHeightPercent: 100,
        lineHeightUnit: 'INTRINSIC_%',
      },
      characterStyleOverrides: [1, 1, 1, 1, 2],
      styleOverrideTable: {
        '1': {
          letterSpacing: 1,
        },
        '2': {
          letterSpacing: 0,
        },
      },
    },
    {
      id: '0:21',
      name: 'label-amount',
      type: 'TEXT',
      blendMode: 'NORMAL',
      opacity: 0.5,
      absoluteBoundingBox: {
        x: 409,
        y: 275,
        width: 35,
        height: 9,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'KOGUS',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Medium',
        fontWeight: 500,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 9,
        textAlignHorizontal: 'RIGHT',
        textAlignVertical: 'TOP',
        letterSpacing: 1,
        lineHeightPx: 10.546875,
        lineHeightPercent: 100,
        lineHeightUnit: 'INTRINSIC_%',
      },
      characterStyleOverrides: [],
      styleOverrideTable: {},
    },
    {
      id: '0:22',
      name: 'label-price',
      type: 'TEXT',
      blendMode: 'NORMAL',
      opacity: 0.5,
      absoluteBoundingBox: {
        x: 331,
        y: 275,
        width: 25,
        height: 9,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'HIND',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Medium',
        fontWeight: 500,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 9,
        textAlignHorizontal: 'RIGHT',
        textAlignVertical: 'TOP',
        letterSpacing: 1,
        lineHeightPx: 10.546875,
        lineHeightPercent: 100,
        lineHeightUnit: 'INTRINSIC_%',
      },
      characterStyleOverrides: [],
      styleOverrideTable: {},
    },
    {
      id: '0:20',
      name: 'label-item',
      type: 'TEXT',
      blendMode: 'NORMAL',
      opacity: 0.5,
      absoluteBoundingBox: {
        x: 56,
        y: 275,
        width: 86,
        height: 9,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'TOODE / TEENUS',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Medium',
        fontWeight: 500,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 9,
        textAlignHorizontal: 'LEFT',
        textAlignVertical: 'TOP',
        letterSpacing: 1,
        lineHeightPx: 10.546875,
        lineHeightPercent: 100,
        lineHeightUnit: 'INTRINSIC_%',
      },
      characterStyleOverrides: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
      styleOverrideTable: {
        '1': {
          letterSpacing: 1,
        },
        '2': {
          letterSpacing: 0,
        },
      },
    },
    {
      id: '0:28',
      name: 'credential-values',
      type: 'TEXT',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: {
        x: 437,
        y: 84,
        width: 103,
        height: 70,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'OÜ Mikk Martin\nEE907700771001360230\n2019052201\n22.05.2019\n22.06.2019',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Medium',
        fontWeight: 500,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 9,
        textAlignHorizontal: 'RIGHT',
        textAlignVertical: 'TOP',
        letterSpacing: 0.15000000596046448,
        lineHeightPx: 14,
        lineHeightPercent: 132.74073791503906,
        lineHeightPercentFontSize: 155.55555725097656,
        lineHeightUnit: 'PIXELS',
      },
      characterStyleOverrides: [],
      styleOverrideTable: {},
    },
    {
      id: '0:27',
      name: 'credential-descriptions',
      type: 'TEXT',
      blendMode: 'NORMAL',
      opacity: 0.5018656849861145,
      absoluteBoundingBox: {
        x: 358,
        y: 84,
        width: 64,
        height: 70,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'Saaja nimi\nKonto nr. (LHV)\nArve nr\nKuupäev\nTähtaeg',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Regular',
        fontWeight: 400,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 9,
        textAlignHorizontal: 'RIGHT',
        textAlignVertical: 'TOP',
        letterSpacing: 0,
        lineHeightPx: 14,
        lineHeightPercent: 132.74073791503906,
        lineHeightPercentFontSize: 155.55555725097656,
        lineHeightUnit: 'PIXELS',
      },
      characterStyleOverrides: [],
      styleOverrideTable: {},
    },
    {
      id: '0:19',
      name: 'topay-summary-value',
      type: 'TEXT',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: {
        x: 389,
        y: 176,
        width: 151,
        height: 34,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: '1 800.00€',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Regular',
        fontWeight: 400,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 34,
        textAlignHorizontal: 'RIGHT',
        textAlignVertical: 'TOP',
        letterSpacing: 0,
        lineHeightPx: 39.84375,
        lineHeightPercent: 100,
        lineHeightUnit: 'INTRINSIC_%',
      },
      characterStyleOverrides: [],
      styleOverrideTable: {},
    },
    {
      id: '0:9',
      name: 'topay-summary-description',
      type: 'TEXT',
      blendMode: 'NORMAL',
      opacity: 0.5018656849861145,
      absoluteBoundingBox: {
        x: 413,
        y: 214,
        width: 127,
        height: 14,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'kuulub maksmisele',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Regular',
        fontWeight: 400,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 14,
        textAlignHorizontal: 'RIGHT',
        textAlignVertical: 'TOP',
        letterSpacing: 0,
        lineHeightPx: 16.40625,
        lineHeightPercent: 100,
        lineHeightUnit: 'INTRINSIC_%',
      },
      characterStyleOverrides: [],
      styleOverrideTable: {},
    },
    {
      id: '1:101',
      name: 'To',
      type: 'FRAME',
      blendMode: 'PASS_THROUGH',
      children: [
        {
          id: '0:3',
          name: 'To-title',
          type: 'TEXT',
          blendMode: 'PASS_THROUGH',
          absoluteBoundingBox: {
            x: 55,
            y: 182,
            width: 117,
            height: 30,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          layoutAlign: 'MIN',
          fills: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
            },
          ],
          strokes: [],
          strokeWeight: 0,
          strokeAlign: 'CENTER',
          exportSettings: [],
          effects: [],
          characters: 'Dashbird OÜ',
          style: {
            fontFamily: 'Wigrum',
            fontPostScriptName: 'Wigrum-Medium',
            fontWeight: 500,
            textAutoResize: 'WIDTH_AND_HEIGHT',
            fontSize: 20,
            textAlignHorizontal: 'LEFT',
            textAlignVertical: 'TOP',
            letterSpacing: -0.5,
            lineHeightPx: 30,
            lineHeightPercent: 128,
            lineHeightPercentFontSize: 150,
            lineHeightUnit: 'FONT_SIZE_%',
          },
          characterStyleOverrides: [],
          styleOverrideTable: {},
        },
        {
          id: '0:26',
          name: 'To-description',
          type: 'TEXT',
          blendMode: 'NORMAL',
          opacity: 0.5018656849861145,
          absoluteBoundingBox: {
            x: 55,
            y: 212,
            width: 315,
            height: 18,
          },
          constraints: {
            vertical: 'TOP',
            horizontal: 'LEFT',
          },
          layoutAlign: 'CENTER',
          fills: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 1,
              },
            },
          ],
          strokes: [],
          strokeWeight: 0,
          strokeAlign: 'CENTER',
          exportSettings: [],
          effects: [],
          characters: 'Brändi värskendus ja veebisaidi uuendus',
          style: {
            fontFamily: 'Wigrum',
            fontPostScriptName: 'Wigrum-Regular',
            fontWeight: 400,
            textAutoResize: 'HEIGHT',
            fontSize: 14,
            textAlignHorizontal: 'LEFT',
            textAlignVertical: 'BOTTOM',
            letterSpacing: 0,
            lineHeightPx: 18,
            lineHeightPercent: 109.71427917480469,
            lineHeightPercentFontSize: 128.57142639160156,
            lineHeightUnit: 'PIXELS',
          },
          characterStyleOverrides: [],
          styleOverrideTable: {},
        },
      ],
      absoluteBoundingBox: {
        x: 55,
        y: 182,
        width: 315,
        height: 48,
      },
      constraints: {
        vertical: 'BOTTOM',
        horizontal: 'LEFT',
      },
      clipsContent: true,
      background: [],
      fills: [],
      strokes: [],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      backgroundColor: {
        r: 0,
        g: 0,
        b: 0,
        a: 0,
      },
      layoutGrids: [],
      layoutMode: 'VERTICAL',
      effects: [],
    },
    {
      id: '0:8',
      name: 'From-description',
      type: 'TEXT',
      blendMode: 'NORMAL',
      opacity: 0.5018656849861145,
      absoluteBoundingBox: {
        x: 55,
        y: 121,
        width: 293,
        height: 14,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'Digitaalne disain',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Regular',
        fontWeight: 400,
        textAutoResize: 'HEIGHT',
        fontSize: 14,
        textAlignHorizontal: 'LEFT',
        textAlignVertical: 'TOP',
        letterSpacing: 0,
        lineHeightPx: 16.40625,
        lineHeightPercent: 100,
        lineHeightUnit: 'INTRINSIC_%',
      },
      characterStyleOverrides: [],
      styleOverrideTable: {},
    },
    {
      id: '0:25',
      name: 'From',
      type: 'TEXT',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: {
        x: 52,
        y: 72,
        width: 286,
        height: 46,
      },
      constraints: {
        vertical: 'TOP',
        horizontal: 'LEFT',
      },
      fills: [
        {
          blendMode: 'NORMAL',
          type: 'SOLID',
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 1,
          },
        },
      ],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      exportSettings: [],
      effects: [],
      characters: 'OÜ Mikk Martin',
      style: {
        fontFamily: 'Wigrum',
        fontPostScriptName: 'Wigrum-Regular',
        fontWeight: 400,
        textAutoResize: 'WIDTH_AND_HEIGHT',
        fontSize: 46,
        textAlignHorizontal: 'LEFT',
        textAlignVertical: 'TOP',
        letterSpacing: -4.150000095367432,
        lineHeightPx: 53.90625,
        lineHeightPercent: 100,
        lineHeightUnit: 'INTRINSIC_%',
      },
      characterStyleOverrides: [],
      styleOverrideTable: {},
    },
  ],
  absoluteBoundingBox: {
    x: -2.842170943040401e-14,
    y: 7.105427357601002e-15,
    width: 595,
    height: 842,
  },
  constraints: {
    vertical: 'SCALE',
    horizontal: 'SCALE',
  },
  clipsContent: true,
  background: [
    {
      blendMode: 'NORMAL',
      type: 'SOLID',
      color: {
        r: 1,
        g: 1,
        b: 1,
        a: 1,
      },
    },
  ],
  fills: [
    {
      blendMode: 'NORMAL',
      type: 'SOLID',
      color: {
        r: 1,
        g: 1,
        b: 1,
        a: 1,
      },
    },
  ],
  strokes: [],
  strokeWeight: 1,
  strokeAlign: 'INSIDE',
  backgroundColor: {
    r: 1,
    g: 1,
    b: 1,
    a: 1,
  },
  layoutGrids: [],
  exportSettings: [
    {
      suffix: '',
      format: 'SVG',
      constraint: {
        type: 'SCALE',
        value: 1,
      },
    },
  ],
  effects: [],
}
